name: Provision Tenant Supabase Project

on:
  workflow_dispatch:
    inputs:
      tenant_id:
        description: Tenant UUID
        required: true
      subdomain:
        description: Subdomain
        required: true
      display_name:
        description: Display name
        required: true
      region:
        description: Supabase region
        required: true
        default: us-east-1

jobs:
  provision:
    runs-on: ubuntu-latest
    environment: SERVER
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || 'main' }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt requests

      - name: Debug script excerpt
        run: |
          echo 'Showing script lines 42-60 to verify db_pass payload:'
          sed -n '42,60p' scripts/provision_tenant.py

      - name: Provision project and store creds
        id: provision
        env:
          SUPABASE_PAT: ${{ secrets.SUPABASE_PAT }}
          SUPABASE_ORG_ID: ${{ secrets.SUPABASE_ORG_ID }}
          CONTROL_PLANE_API_URL: ${{ secrets.CONTROL_PLANE_API_URL }}
          DEFAULT_TENANT_DB_PASSWORD: ${{ secrets.DEFAULT_TENANT_DB_PASSWORD }}
        run: |
          python scripts/provision_tenant.py \
            --tenant-id '${{ github.event.inputs.tenant_id }}' \
            --subdomain '${{ github.event.inputs.subdomain }}' \
            --display-name '${{ github.event.inputs.display_name }}' \
            --region '${{ github.event.inputs.region }}'

      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run school schema migrations via psql (Supavisor)
        env:
          REGION: ${{ github.event.inputs.region }}
          PROJECT_REF: ${{ steps.provision.outputs.project_ref }}
          DB_PASS: ${{ secrets.DEFAULT_TENANT_DB_PASSWORD }}
        run: |
          echo "Applying SQL to tenant DB via Supavisor"
          HOST="aws-0-$REGION.pooler.supabase.com"
          export PGPASSWORD="$DB_PASS"
          psql -h "$HOST" -p 6543 -U "postgres.$PROJECT_REF" -d postgres -v ON_ERROR_STOP=1 -f app/prisma/tenant_schema.sql | sed -e 's/.\{200\}/&\n/g' | head -n 1000


