name: Provision Tenant Supabase Project

on:
  workflow_dispatch:
    inputs:
      tenant_id:
        description: Tenant UUID
        required: true
      subdomain:
        description: Subdomain
        required: true
      display_name:
        description: Display name
        required: true
      region:
        description: Supabase region
        required: true
        default: us-east-1

jobs:
  provision:
    runs-on: ubuntu-latest
    environment: SERVER
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || 'main' }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt requests

      - name: Debug script excerpt
        run: |
          echo 'Showing script lines 42-60 to verify db_pass payload:'
          sed -n '42,60p' scripts/provision_tenant.py

      - name: Provision project and store creds
        id: provision
        env:
          SUPABASE_PAT: ${{ secrets.SUPABASE_PAT }}
          SUPABASE_ORG_ID: ${{ secrets.SUPABASE_ORG_ID }}
          CONTROL_PLANE_API_URL: ${{ secrets.CONTROL_PLANE_API_URL }}
          DEFAULT_TENANT_DB_PASSWORD: ${{ secrets.DEFAULT_TENANT_DB_PASSWORD }}
        run: |
          python scripts/provision_tenant.py \
            --tenant-id '${{ github.event.inputs.tenant_id }}' \
            --subdomain '${{ github.event.inputs.subdomain }}' \
            --display-name '${{ github.event.inputs.display_name }}' \
            --region '${{ github.event.inputs.region }}'

      - name: Install Supabase CLI
        run: |
          set -e
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then ARCH=amd64; fi
          VERSION=$(curl -s https://api.github.com/repos/supabase/cli/releases/latest | grep tag_name | cut -d '"' -f4)
          URL="https://github.com/supabase/cli/releases/download/${VERSION}/supabase_${VERSION#v}_linux_${ARCH}.deb"
          curl -fsSL -o supabase.deb "$URL"
          sudo dpkg -i supabase.deb
          supabase --version

      - name: Run school schema migrations via Supabase CLI
        env:
          REGION: ${{ github.event.inputs.region }}
          PROJECT_REF: ${{ steps.provision.outputs.project_ref }}
          DB_PASS: ${{ secrets.DEFAULT_TENANT_DB_PASSWORD }}
          TENANT_ID: ${{ github.event.inputs.tenant_id }}
          SUBDOMAIN: ${{ github.event.inputs.subdomain }}
        run: |
          echo "Applying SQL to tenant DB via Supabase CLI"
          HOST="aws-1-$REGION.pooler.supabase.com"
          echo "Tenant: $TENANT_ID | Subdomain: $SUBDOMAIN"
          echo "Region: $REGION | Project ref: $PROJECT_REF"
          echo "Pooler host: $HOST"
          echo "DB user (session): postgres.$PROJECT_REF"
          echo "DB user (options): postgres with options=project=$PROJECT_REF"
          echo "Masking DB_PASS"; echo "::add-mask::$DB_PASS"; echo "Length(DB_PASS)=${#DB_PASS}"
          printf "%s" "$DB_PASS" | sha256sum | awk '{print "DB_PASS sha256 (first 8): " substr($1,1,8)}'
          # Build the single, expected transaction pooler DSN
          ENC_PASS=$(python3 -c "import os,urllib.parse;print(urllib.parse.quote(os.environ['DB_PASS']))")
          echo "::add-mask::$ENC_PASS"
          DB_URL="postgresql://postgres.${PROJECT_REF}:${ENC_PASS}@${HOST}:6543/postgres?sslmode=require"
          echo "Checking DB readiness via supabase db pull"
          READY=0
          for i in $(seq 1 120); do
            echo "Attempt $i: pull with user=postgres.$PROJECT_REF"
            if supabase db pull --db-url "$DB_URL" --workdir ./supabase --debug > /dev/null 2>&1; then READY=1; break; fi
            sleep 5
          done
          if [ $READY -ne 1 ]; then
            echo "Database not ready after waiting. Exiting." >&2
            exit 1
          fi

          echo "DB ready. Applying migration"; mkdir -p supabase/migrations; TS=$(date +%s); cp app/prisma/tenant_schema.sql "supabase/migrations/${TS}_tenant_schema.sql"; supabase db push --db-url "$DB_URL" --workdir ./supabase --yes --debug; echo "Verifying schema..."; supabase db pull --db-url "$DB_URL" --workdir ./supabase --debug | head -n 100


